[phases.setup]
nixpkgs = [
  "php82.withExtensions (pe: [ pe.mysqli pe.pdo_mysql pe.mongodb ])",
  "nginx",
  "libmysqlclient",
  "php82Packages.composer",
  "nodejs_18",
  "npm-9_x"
]

[phases.build]
commands = [
  "composer install --ignore-platform-reqs",
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx"
]

[phases.start]
commands = [
  "php-fpm -y /etc/php/8.2/fpm/php-fpm.conf & nginx -g 'daemon off;'"
]
