[phases.setup]
nixpkgs = [
  "php74.withExtensions (pe: [ pe.mysqli pe.pdo_mysql pe.mongodb ])",
  "nginx",
  "libmysqlclient",
  "php74Packages.composer",
  "nodejs_18",
  "npm-9_x"
]

[phases.build]
commands = [
  "composer install --ignore-platform-reqs"
]

[phases.start]
commands = [
  "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
]
