[phases.setup]
apt_dependencies = ["libpng-dev", "libjpeg-dev", "libfreetype6-dev", "libonig-dev", "libxml2-dev", "libzip-dev", "unzip", "git"]

[phases.build]
commands = [
  "composer install",
  "pecl channel-update pecl.php.net",
  "echo 'extension=mongodb.so' > /usr/local/etc/php/conf.d/mongodb.ini"
]