[phases.setup]
apt_dependencies = ["software-properties-common", "php-pear", "php-dev", "libpng-dev", "libjpeg-dev", "libfreetype6-dev", "libonig-dev", "libxml2-dev", "libzip-dev", "unzip", "git"]

[phases.build]
commands = [
  "sudo add-apt-repository ppa:ondrej/php",
  "sudo apt-get update",
  "sudo apt-get install -y php-mongodb",
  "composer install --ignore-platform-reqs"
]